=== api-evangelist/dexcom/json-schema/dexcom-api-alerts-response-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/dexcom/refs/heads/main/json-schema/dexcom-api-alerts-response-schema.json",
  "title": "AlertsResponse",
  "description": "AlertsResponse schema from Dexcom Developer API",
  "type": "object",
  "properties": {
    "recordType": {
      "type": "string",
      "example": "alert"
    },
    "recordVersion": {
      "type": "string",
      "example": "3.0"
    },
    "userId": {
      "type": "string"
    },
    "records": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/AlertRecord"
      }
    }
  },
  "$defs": {
    "AlertRecord": {
      "type": "object",
      "properties": {
        "recordId": {
          "type": "string"
        },
        "systemTime": {
          "$ref": "#/$defs/DateTime"
        },
        "displayTime": {
          "$ref": "#/$defs/DateTime"
        },
        "alertName": {
          "$ref": "#/$defs/AlertName"
        },
        "alertState": {
          "$ref": "#/$defs/AlertState"
        },
        "displayDevice": {
          "type": "string"
        },
        "transmitterGeneration": {
          "$ref": "#/$defs/TransmitterGeneration"
        },
        "transmitterId": {
          "type": "string",
          "nullable": true
        }
      }
    },
    "TransmitterGeneration": {
      "type": "string",
      "enum": [
        "unknown",
        "g4",
        "g5",
        "g6",
        "g6+",
        "dexcomPro",
        "g7"
      ]
    },
    "AlertName": {
      "type": "string",
      "enum": [
        "unknown",
        "high",
        "low",
        "rise",
        "fall",
        "outOfRange",
        "urgentLow",
        "urgentLowSoon",
        "noReadings",
        "fixedLow"
      ]
    },
    "AlertState": {
      "type": "string",
      "enum": [
        "unknown",
        "inactive",
        "activeSnoozed",
        "activeAlarming"
      ]
    },
    "DateTime": {
      "type": "string",
      "format": "date-time",
      "description": "ISO 8601 timestamp."
    }
  }
}

=== api-evangelist/dexcom/examples/dexcom-api-calibrations-response-example.json
{
  "recordType": "calibration",
  "recordVersion": "3.0",
  "userId": "f413c0db-48e5-6f11-c4ff-4d4679c500e5",
  "records": [
    {
      "recordId": "8c2b4627-3a21-6f0b-43ad-fc3e58a42360",
      "systemTime": "2026-04-30T15:00:00",
      "displayTime": "2026-04-30T15:00:00",
      "unit": "mg/dL",
      "value": 123,
      "displayDevice": "receiver",
      "transmitterId": "8GZ7K2",
      "transmitterTicks": 23106960,
      "transmitterGeneration": "g5"
    },
    {
      "recordId": "8ea63c35-e4de-6bad-592e-abf1dd36a681",
      "systemTime": "2026-04-30T15:00:00",
      "displayTime": "2026-04-30T15:00:00",
      "unit": "unknown",
      "value": 129,
      "displayDevice": "receiver",
      "transmitterId": "8GA1JK",
      "transmitterTicks": 85445036,
      "transmitterGeneration": "g4"
    }
  ]
}

=== api-evangelist/dexcom/examples/dexcom-api-devices-response-example.json
{
  "recordType": "device",
  "recordVersion": "3.0",
  "userId": "fd403d5c-d2db-7f03-128a-fbaee573759d",
  "records": [
    {
      "lastUploadDate": "2026-04-30T15:00:00",
      "transmitterId": "8GA1JK",
      "transmitterGeneration": "g6+",
      "displayDevice": "receiver",
      "displayApp": "Dexcom G7",
      "alertSchedules": [
        null,
        null
      ]
    },
    {
      "lastUploadDate": "2026-04-30T15:00:00",
      "transmitterId": "8GA1JK",
      "transmitterGeneration": "g6",
      "displayDevice": "iOS",
      "displayApp": "Dexcom ONE",
      "alertSchedules": [
        null,
        null
      ]
    }
  ]
}

=== api-evangelist/dexcom/examples/dexcom-api-alerts-response-example.json
{
  "recordType": "alert",
  "recordVersion": "3.0",
  "userId": "4c2b0e93-e540-de81-f3a6-f37eea7a6b7d",
  "records": [
    {
      "recordId": "9714fd54-ac32-dab7-38b4-dfdab5a43efb",
      "systemTime": "2026-04-30T15:00:00",
      "displayTime": "2026-04-30T15:00:00",
      "alertName": "urgentLow",
      "alertState": "unknown",
      "displayDevice": "android",
      "transmitterGeneration": "unknown",
      "transmitterId": "8HX3LM"
    },
    {
      "recordId": "2a26df5d-3133-d932-7c72-cee3195b7530",
      "systemTime": "2026-04-30T15:00:00",
      "displayTime": "2026-04-30T15:00:00",
      "alertName": "fall",
      "alertState": "unknown",
      "displayDevice": "iOS",
      "transmitterGeneration": "g5",
      "transmitterId": "8HX3LM"
    }
  ]
}

=== api-evangelist/dexcom/examples/dexcom-api-egvs-response-example.json
{
  "recordType": "egv",
  "recordVersion": "3.0",
  "userId": "079a528d-7cf7-d4b4-7704-1efbd08f921d",
  "records": [
    {
      "recordId": "3f17180d-5a7e-8450-09c8-cb7e76447107",
      "systemTime": "2026-04-30T15:00:00",
      "displayTime": "2026-04-30T15:00:00",
      "transmitterId": "8HX3LM",
      "transmitterTicks": 64309839,
      "value": 138,
      "status": "high",
      "trend": "fortyFiveUp",
      "trendRate": -0.8,
      "unit": "mg/dL",
      "rateUnit": "unknown",
      "displayDevice": "receiver",
      "transmitterGeneration": "dexcomPro"
    },
    {
      "recordId": "f95eee1e-084d-5f22-94c0-031d4d706294",
      "systemTime": "2026-04-30T15:00:00",
      "displayTime": "2026-04-30T15:00:00",
      "transmitterId": "8HX3LM",
      "transmitterTicks": 73688690,
      "value": 135,
      "status": "high",
      "trend": "rateOutOfRange",
      "trendRate": 0.6,
      "unit": "unknown",
      "rateUnit": "mmol/L/min",
      "displayDevice": "android",
      "transmitterGeneration": "g5"
    }
  ]
}

=== api-evangelist/dexcom/examples/dexcom-api-events-response-example.json
{
  "recordType": "event",
  "recordVersion": "3.0",
  "userId": "cafee42b-f0a6-2225-de69-3cb31f95d3b2",
  "records": [
    {
      "recordId": "904a7edc-cd1a-c412-da38-cac0d7e3be27",
      "systemTime": "2026-04-30T15:00:00",
      "displayTime": "2026-04-30T15:00:00",
      "eventType": "exercise",
      "eventSubType": "example",
      "value": 43.67,
      "unit": "mmol/L",
      "eventStatus": "created",
      "transmitterId": "8GA1JK",
      "transmitterGeneration": "unknown",
      "displayDevice": "receiver"
    },
    {
      "recordId": "e837cf43-7827-e026-613b-7f255cfaaaad",
      "systemTime": "2026-04-30T15:00:00",
      "displayTime": "2026-04-30T15:00:00",
      "eventType": "exercise",
      "eventSubType": "example",
      "value": 71.32,
      "unit": "units",
      "eventStatus": "created",
      "transmitterId": "8GZ7K2",
      "transmitterGeneration": "g6+",
      "displayDevice": "android"
    }
  ]
}
